### PR TITLE
Wrap Tooltip children

### LINKED ISSUE #840: Make `tooltipProps` work even if the `Button` is `disabled`
https://www.loom.com/share/cfecf98b2ba84dcaac476473ec01564a

@jagannathBhat _a
This is a bug. Which means, this issue has priority over other assigned issues. If you get assigned with higher priority issues, then please make sure to let me know, so that I can reassign this issue to someone else.

cc: @ajmaln @praveen-murali-ind

### PR DESCRIPTION
**Pull request by jagannathBhat**
Closes #840

### CODE REVIEW

**Comment by jagannathBhat** [comment]
@praveen-murali-ind Please review

**Comment by amaldinesh7** [comment]
This solution will result in wrapping all the elements with a span tag wherever there is a tooltip, which might cause some side effects. We need to test this thoroughly before merging. Thus currently putting on-hold. If this is some blocker in any project, please add the necessary fix in the project end.

cc: @praveen-murali-ind @karthiknmenon

**Comment by jagannathBhat** [comment]
I wrapped the children in a span tag is because the problem is caused by the `tippyjs` package used to build the Tooltip component. I couldn't find any way to override its config to solve the problem.

**Comment by yedhink** [comment]
@amaldinesh7 What are the issues with wrapping the `Button` within a `div` if `tooltipProps` are present? Please note that I am talking about modifying the Button component conditionally. NOT the Tooltip component. Refer: https://github.com/atomiks/tippyjs/issues/286#issuecomment-417966118

cc: @jagannathBhat

**Comment by jagannathBhat** [comment]
> @amaldinesh7 What are the issues with wrapping the `Button` within a `div` if `tooltipProps` are present? Please note that I am talking about modifying the Button component conditionally. NOT the Tooltip component. Refer: [atomiks/tippyjs#286 (comment)](https://github.com/atomiks/tippyjs/issues/286#issuecomment-417966118)
> 
> cc: @jagannathBhat

I chose to edit the `Tooltip` component is because the issue will affect any child component that can be disabled.

**Comment by amaldinesh7** [comment]
I strongly suggest making this change in the respective project end, as showing a tooltip on a disabled element is kind of a rare scenario. Let me know your thoughts. @jagannathBhat  @yedhink

cc: @karthiknmenon @praveen-murali-ind 


> @amaldinesh7 What are the issues with wrapping the `Button` within a `div` if `tooltipProps` are present? Please note that I am talking about modifying the Button component conditionally. NOT the Tooltip component. Refer: [atomiks/tippyjs#286 (comment)](https://github.com/atomiks/tippyjs/issues/286#issuecomment-417966118)
> 
> cc: @jagannathBhat

Like I said showing a Tooltip on button(which does not have a disabled state) is very common throughout the products. So if we add a `div` or `span` to wrap the button, we'll end up having an unwanted wrapper for the button in a lot of places.

**Pull request closed without merging**
