### PR TITLE
Handled edge case where formikContext is nil

### PR DESCRIPTION
**Pull request by jagannathBhat**
Related to bigbinary/neeto-desk-web#20053

**Description**

Handles the case where `BlockNavigation` is used without formik.

**Checklist**

- [ ] ~I have made corresponding changes to the documentation.~
- [ ] ~I have updated the types definition of modified exports.~
- [x] I have verified the functionality in some of the neeto web-apps.
- [ ] ~I have added tests that prove my fix is effective or that my feature works.~
- [ ] ~I have added proper `data-cy` and `data-testid` attributes.~
- [x] I have added the necessary label (`patch`/`minor`/`major` - If package publish
      is required).

**Reviewers**

### CODE REVIEW

**Comment by jagannathBhat** [comment]
@josephmathew900 _a Please review

**Review by josephmathew900 — COMMENTED** [review]
@jagannathBhat _a https://joseph-mathew.neetorecord.com/watch/37e27024-acfc-493e-8004-fdb1bc6d8a28

**Comment by jagannathBhat** [comment]
@josephmathew900 _a https://jagannath-bhat.neetorecord.com/watch/1d61b89f-c6ce-4172-8bd4-c40477c06554

**Comment by josephmathew900** [comment]
@jagannathBhat I'm merging this PR to fix the crash, but as we discussed in the call, we need to make some changes on the NeetoDesk side also for the functionality to work properly.

**Review by josephmathew900 — APPROVED** [review]
LGTM

**Pull request merged**
