### PR TITLE
Added Popover component

### LINKED ISSUE #1449: Add Popover component
Ref - https://github.com/bigbinary/neeto-engineering-ui-ux/issues/66

[Figma design](https://www.figma.com/file/Osl7GBbBk0iwVMc57366nZ/neetoKB?node-id=4458%3A25781&t=0RJBVhlciSSiDLq5-0)

@amaldinesh7 _A @goutham-subramanyam _A

### PR DESCRIPTION
**Pull request by goutham-subramanyam**
Fixes #1449 

**Description**

- Added: _Popover_ component

Screenshot 2022-12-05 at 5 42 51 PM

**Checklist**

- [x] I have performed a self-review of my code
- [x] I have made corresponding changes to the documentation
- [x] ~I have added tests that prove my fix is effective or that my feature works~
- [x] I have added the necessary label (patch/minor/major - If package publish is required)
- [x] I have followed the suggested description format and styling

**Reviewers**

@praveen-murali-ind _a Please check and merge.

cc: @amaldinesh7

### CODE REVIEW

**Comment by praveen-murali-ind** [comment]
@goutham-subramanyam _a Please work on the changes discussed over the call.

**Comment by goutham-subramanyam** [comment]
@praveen-murali-ind _a Made the changes. Please check.

**Comment by praveen-murali-ind** [comment]
@goutham-subramanyam LGTM. @amaldinesh7 @karthiknmenon Please review.

**Review by karthiknmenon — COMMENTED** [review]
@deepakjosp _a Could you please add tests for this component? I have a few suggestions, let's discuss that on call.

**Comment by karthiknmenon** [comment]
@karthiknmenon _a Taking this up.

cc: @praveen-murali-ind

**Comment by karthiknmenon** [comment]
@amaldinesh7 _a Please review.

**Review by amaldinesh7 — APPROVED** [review]

**Pull request merged**
