### PR TITLE
Moved loader position to center

### LINKED ISSUE #2192: Shifting of button when submit is hit
Reference: https://github.com/bigbinary/neeto-engineering-ui-ux/issues/282

@thomas-mathai _a

### PR DESCRIPTION
**Pull request by thomas-mathai**
- Fixes #2192 

**Checklist**

- [ ] ~I have made corresponding changes to the documentation.~
- [ ] ~I have updated the types definition of modified exports~
- [ ] ~I have verified the functionality in some of the neeto web-apps.~
- [ ] ~I have added tests that prove my fix is effective or that my feature works.~
- [ ] ~I have added proper `data-cy` and `data-testid` attributes.~
- [x] I have added the necessary label (`patch`/`minor`/`major` - If package publish
      is required).

**Reviewers**

https://github.com/bigbinary/neeto-ui/assets/85351738/3d786722-8fbe-4650-a744-e5f49f0d32fc

### CODE REVIEW

**Comment by thomas-mathai** [comment]
@praveen-murali-ind _a Can you please check?

**Comment by praveen-murali-ind** [comment]
@ajmaln _a Could you please review? I have removed the motion instance from neetoUI button since the loading style has changed and it is no longer needed.

**Comment by praveen-murali-ind** [comment]
@ajmaln Please assign the PR back to me once reviewed. We can assign someone to test the new loading style on the priority products.

**Review by ajmaln — APPROVED** [review]
Looks good

@praveen-murali-ind _a

**Comment by praveen-murali-ind** [comment]
@thomas-mathai _a As discussed, let’s cross-test the changes in the priority products.

**Comment by thomas-mathai** [comment]
@praveen-murali-ind I have verified the changes in `NeetoCal` and `NeetoInvoice`. Loading state is working fine.

**Comment by thomas-mathai** [comment]
@deepakjosp _a There are some issues with the `Avatar` component. Could you please check the CI checks?

**Comment by deepakjosp** [comment]
@thomas-mathai _a the branch had the old avatar component. It is fixed by rebasing. Please check.

**Pull request merged**
