### PR TITLE
Color picker improvements

### LINKED ISSUE #2374: Better color picker
Ref - https://github.com/bigbinary/neeto-engineering-ui-ux/issues/353

[Figma](https://www.figma.com/design/YxylhnvBCVt1PrhWV3WIQb/neetoCal?node-id=6423-22574&t=UJ5Rmt5BCwpeyHDf-1)

@praveen-murali-ind _A

### PR DESCRIPTION
**Pull request by praveen-murali-ind**
- Fixes #2374 

### Changes

- Improved: spacing.
- Enabled: # prefix displaying.
- Enabled: eye picker by default.
- Updated: color palette styles.
- Updated: color input styles.
- Updated: color picker icon.

Screenshot 2024-11-27 at 2 26 58 PM

<br>

Screenshot 2024-11-27 at 10 29 29 AM

**Description**

**Checklist**

- [ ] I have made corresponding changes to the documentation.
- [ ] I have updated the types definition of modified exports.
- [ ] I have verified the functionality in some of the neeto web-apps.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] I have added proper `data-cy` and `data-testid` attributes.
- [x] I have added the necessary label (`patch`/`minor`/`major` - If package publish
      is required).

**Reviewers**

@deepakjosp _A

### CODE REVIEW

**Comment by praveen-murali-ind** [comment]
@deepakjosp _a Could you please work on the following?

- [ ] Show color palette by default. For now we can use the color values in the Storybook. 

Screenshot 2024-11-27 at 2 37 25 PM

**Comment by deepakjosp** [comment]
@praveen-murali-ind as per our discussion let's refactor the Palette component to avoid the tailwind dependency and implement a more straight forward and simple way similar to what the `react-colorful` has implemented for the color boxes. This includes the change in the color list prop of the palette to array of color values and use those instead of the color bg classes and gradient as an inline style. Also these are breaking changes, we will have to refactor the usages in NeetoDesk and NeetoWireframe.

cc: @josephmathew900

**Comment by deepakjosp** [comment]
@praveen-murali-ind let's merge the PR with the current changes. Color palette changes can be taken up as a separate [issue](https://github.com/bigbinary/neeto-ui/issues/2390).

**Comment by deepakjosp** [comment]
@josephmathew900 _a I've updated the jest.config. Please review.

**Review by josephmathew900 — APPROVED** [review]
LGTM

**Pull request merged**
