### PR TITLE
Replaced info Icon with Help icon in Label component

### LINKED ISSUE #2085: Make Help icon as default icon in Label ocomponent
part of https://github.com/bigbinary/neeto-engineering-ui-ux/issues/223

Keeping the Help icon as the default icon in the [Label](https://neeto-ui.neeto.com/?path=/docs/components-label--docs) component will fix the below usage of info icons 

Screenshot 2024-02-13 at 8 44 45 PM

Screenshot 2024-02-13 at 8 55 47 PM

https://github.com/bigbinary/neeto-ui/blob/3e783d42030af401fd28fd150c3e26b5a8c5a52e/src/components/Label.jsx#L24

cc: @praveen-murali-ind  @akkshaylawrence

### PR DESCRIPTION
**Pull request by nitinprojects**
- Fixes #2085

**Description**

Before

Screenshot 2024-02-15 at 5 47 48 PM

After

2a-after

---

Before

3-before

After

Screenshot 2024-02-21 at 11 32 00 PM

**Checklist**

~- [ ] I have made corresponding changes to the documentation.~
~- [ ] I have updated the types definition of modified exports.~
- [x] I have verified the functionality in some of the neeto web-apps.
~- [ ] I have added tests that prove my fix is effective or that my feature works.~
~- [ ] I have added proper `data-cy` and `data-testid` attributes.~
- [x] I have added the necessary label (`patch`/`minor`/`major` - If package publish
      is required).

**Reviewers**

### CODE REVIEW

**Comment by nitinprojects** [comment]
@akkshaylawrence _a Please review.

cc: @praveen-murali-ind

**Comment by nitinprojects** [comment]
@farhanlatheef _a Please review.

**Review by farhanlatheef — APPROVED** [review]

**Comment by josephmathew900** [comment]
@nitinprojects _a

Please fix the eslint errors. Also, please assign the PR for review only when all the required checks have been passed.

image

**Comment by nitinprojects** [comment]
@josephmathew900 _a  Fixed the eslint errors. Please check.

**Review by josephmathew900 — APPROVED** [review]
LGTM.

**Pull request merged**
