### PR TITLE
Add appswitcher to layouts

### LINKED ISSUE #447: Add App Switcher to neetoui layouts.
I was thinking on the app switcher part feels like to don't need to have a separate package just for 1 file. We could add that on the neetoui layouts. 

@karthiknmenon Let me know your thoughts

### PR DESCRIPTION
**Pull request by edwinbbu**
Fixes #447 
Screenshot
Screenshot 2021-09-15 at 2 42 21 PM

@praveen-murali-ind _a Please clean up the UI. I have wired the functionality

cc @karthiknmenon

### CODE REVIEW

**Comment by edwinbbu** [comment]
@praveen-murali-ind Can you resolve the deployment failure
Screenshot 2021-09-16 at 8 06 37 PM

**Comment by praveen-murali-ind** [comment]
Applied styles 

Fixes #454 #447

@karthiknmenon _a Please review.

//cc @edwinbbu 

Screenshot 2021-09-17 at 12 55 04 PM
Screenshot 2021-09-17 at 12 54 34 PM

**Comment by karthiknmenon** [comment]
@edwinbbu Please cross-check how we will be handling subdomains based on different organizations.

**Comment by karthiknmenon** [comment]
@edwinbbu _a Please cross-check how we will be handling subdomains based on different organizations.

**Comment by edwinbbu** [comment]
> @edwinbbu _a Please cross-check how we will be handling subdomains based on different organizations.

@ghousemohamed Would like your thoughts on the same. Could we get on a call?

**Comment by edwinbbu** [comment]
@karthiknmenon On discussion with @ghousemohamed. We decided to get the subdomain from the URL. Trying out the approach.

**Comment by edwinbbu** [comment]
@karthiknmenon _a Handled the subdomain issue.
Tested out the changes in neetoInterview and here is a quick demo.
https://www.loom.com/share/9a0c6c76467f4b8a987d8c95c3a03262

cc @praveen-murali-ind, @unnitallman

**Comment by karthiknmenon** [comment]
LGTM.

**Pull request merged**
