### PR TITLE
Added eyedropper to ColorPicker

### LINKED ISSUE #1363: Check feasibility of adding an eye dropper in ColorPicker
It would be nice to have an eye dropper in `ColorPicker` component. We have a use case in neetoForm theming to pick a color from a background image.

image

### LINKED ISSUE #1388: Issue with ColorPicker initial value
The color picker, when having an initial value passed for the `color` prop, the slider fails to response to sliding. This is mostly noted when the color value is black (#000000) or white (#FFFFFF).

[Video](https://www.loom.com/share/6f0c44cb613e4be688243cd1c27f0440)
Please have a look

@amaldinesh7 _a

Related issue in neetoForm: https://github.com/bigbinary/neeto-form-web/issues/4638

### PR DESCRIPTION
**Pull request by amaldinesh7**
Fixes #1388 
Fixes #1363 

**Description**

- Added: Eyedropper to _ColorPicker_

**Checklist**

- [ ] I have performed a self-review of my code
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added the necessary label (patch/minor/major - If package publish is required)
- [ ] I have followed the suggested description format and styling

**Reviewers**

### CODE REVIEW

**Comment by amaldinesh7** [comment]
@praveen-murali-ind _a Please fix the styles.

**Comment by praveen-murali-ind** [comment]
@karthiknmenon _a I have fixed the UI issues. I think we should provide one prop to hide the hex field to create UI like below. Could you please share your thoughts on this.

Group 1

**Comment by karthiknmenon** [comment]
> I think we should provide one prop to hide the hex field to create UI like below. Could you please share your thoughts on this.

@praveen-murali-ind  I agree.

@deepakjosp _a Could you please take this up?

**Comment by praveen-murali-ind** [comment]
@deepakjosp _A

**Comment by deepakjosp** [comment]
@karthiknmenon  _a could you please review the changes?

**Review by karthiknmenon — APPROVED** [review]
Changes LGTM.

@deepakjosp _a Can we add tests for the newly added props? Please assign the PR to Praveen for a final review after this.

**Comment by deepakjosp** [comment]
@karthiknmenon   _a could you please take a look into the unit test for checking saturation slider?

**Comment by karthiknmenon** [comment]
@deepakjosp _a Fixed the failing test. Please confirm and assign the PR to Praveen for a final review.

**Comment by deepakjosp** [comment]
@karthiknmenon changes looks good. Thanks for jumping in. @praveen-murali-ind  _a could you please review this PR?

**Comment by praveen-murali-ind** [comment]
@karthiknmenon _a The changes look good to me. When we opened the deployment app link, it is showing in dark mode by default. But in live it is working fine. Could you please check and merge.

Screenshot 2022-11-03 at 4 06 50 PM

**Pull request merged**
