### PR TITLE
Replace moment.js with Dayjs in DatePicker

### LINKED ISSUE #611: Change the Ant Design DatePicker from moment.js to dayjs in DatePicker component
https://github.com/iamkun/dayjs/issues/529

@amaldinesh7 _a

### PR DESCRIPTION
**Pull request by karthiknmenon**
Fixes #611 

@amaldinesh7 _a Please review.

cc: @ajmaln @edwinbbu

### CODE REVIEW

**Comment by karthiknmenon** [comment]
Fixes #610

**Comment by ajmaln** [comment]
@karthiknmenon the user-provided format is not utilized when `showTime` is `true`. Shouldn't we support the option to format the time as well?

**Comment by karthiknmenon** [comment]
@ajmaln _a Could you please add the same to this PR? For now, I have hardcoded `HH:mm`.

**Comment by ajmaln** [comment]
@amaldinesh7 _a Please review.

**Comment by amaldinesh7** [comment]
@karthiknmenon _a

**Pull request merged**
