### PR TITLE
Added color prop to the `Tag` component

### LINKED ISSUE #2337: Add color prop to `Tag` component
Part of https://github.com/bigbinary/neeto-tags-nano/issues/333

- The `color` prop overrides the `style` property and should have a higher precedence.
- The `color` prop accepts a hexadecimal value. This value will be set as the font-color and border color of the `Tag` component.
- The background color of the `Tag` component will be set to the color with an alpha value of `0.3` (opacity).

enhancement _t
@AbhayVAshokan _a

### PR DESCRIPTION
**Pull request by AbhayVAshokan**
- Fixes #2337 

**Description**

- Added: `color` prop to the `Tag` component.

**Checklist**

- [x] I have made corresponding changes to the documentation.
- [x] I have updated the types definition of modified exports.
- [x] I have verified the functionality in some of the neeto web-apps.
- [x] ~I have added tests that prove my fix is effective or that my feature works.~
- [x] ~I have added proper `data-cy` and `data-testid` attributes.~
- [x] I have added the necessary label (`patch`/`minor`/`major` - If package publish
      is required).

**Reviewers**

@AbhayVAshokan _a
patch _t

### CODE REVIEW

**Comment by AbhayVAshokan** [comment]
@Tsudhishnair _a please use this URL to review. I have built [a custom component to help with the PR review](https://neeto-ui-kpyu-pr-2338.neetodeployapp.com/?path=/story/components-tag--temporary-component).

Here, I have used all the colors provided by the GitHub labels color palette by default. I have added a color picker to test it with different colors.

**Light mode**

image

**Dark mode**

image

- Here, all the colors look good in the dark mode. The lighter colors do not look good in the light mode. 
- GitHub uses a different set of colors for light and dark mode. Hence, the labels look good in all the cases.
- It can be observed that all the colors look good for "solid" type in both the themes.

---

@Tsudhishnair please have a look at the UI and LMK:
- If any further changes need to be taken up for the UI (different calculation).
- The list of colors that would be the best fit for `neeto-tags-nano`. 
- Any other suggestions.

**Comment by praveen-murali-ind** [comment]
@praveen-murali-ind _A Self-assigning to work on the colors.

**Review by praveen-murali-ind — COMMENTED** [review]
@AbhayVAshokan _a, as discussed on the call, let’s remove the new `color` prop and use the existing `style` prop instead.

cc @Tsudhishnair

**Comment by AbhayVAshokan** [comment]
As per the discussion, I am closing this PR. We will add new styles as part of the Tag component and the colors will be added as new styles.

**Pull request closed without merging**
