### PR TITLE
[WIP] Sync Collapse

### PR DESCRIPTION
**Pull request by yedhink**
Fiixes #37 

@edwinbbu _a
Can you give this PR a review and merge it if everything looks good?

### CODE REVIEW

**Comment by goutham-subramanyam** [comment]
@yedhink Collapse component will be updated by @vinay0x in the following [PR](https://github.com/bigbinary/neeto-help-web/pull/8711). So it would be better to merge this after that is done.

**Comment by edwinbbu** [comment]
@goutham-subramanyam _a

**Comment by goutham-subramanyam** [comment]
@yedhink _a

**Comment by yedhink** [comment]
@edwinbbu 
@goutham-subramanyam 

I'm confused. What exactly needs to be done with this issue? If i fix the conflict, can this be merged? I thought we should wait until the other PR is fixed in-order to merge this.

**Comment by goutham-subramanyam** [comment]
@yedhink _a Please fix the conflicts and copy the latest version of `Collapse` from NitroHelp `master`.

**Comment by yedhink** [comment]
@goutham-subramanyam _a

I have fixed the conflicts and used latest Collpase.

Also updated `Card` component with `open` over `show`.

Please review and merge if everything looks good.

**Comment by edwinbbu** [comment]
@yedhink _a Since you have touched the Card component, we can sync the card component in this PR itself otherwise checking diff will become complex.

**Comment by yedhink** [comment]
@edwinbbu _a

I had already synced the `Card` component in https://github.com/bigbinary/neeto-ui/pull/59

@goutham-subramanyam Can you confirm whether there are any other changes, other than changing `show` to `open` in `Card` component in neeto-help? I have only made that change since Card component was already synced once. 

If not, then this is good to be merged I think.

**Pull request merged**
