### PR TITLE
Adds missing typography story lines

### LINKED ISSUE #1333: Add content about neetoUI classnames.
I happened to see `neeto-ui-text-transform-capitalize` classname which help me to reduce the JavaScript required to do the same for the srcibble application.
I found this classname and other classnames while going through the GitHub Repo, but the same was not mentioned, or related content is not present in the current documentation.

@yedhink

### PR DESCRIPTION
**Pull request by deepakjosp**
Fixes #1333 

**Description**
Added: documentation for missing typography styles.

**Checklist**

- [x] I have performed a self-review of my code
- [x] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added the necessary label (patch/minor/major - If package publish is required)
- [x] I have followed the suggested description format and styling

**Reviewers**

### CODE REVIEW

**Comment by deepakjosp** [comment]
@karthiknmenon  _a could you please review this PR?

**Comment by karthiknmenon** [comment]
LGTM.

@praveen-murali-ind _a Could you please confirm and merge?

**Comment by praveen-murali-ind** [comment]
> LGTM.
> 
> @praveen-murali-ind _a Could you please confirm and merge?

@karthiknmenon I think we should move these utilities to helpers page. lmk your thought ?

Screenshot 2022-11-02 at 5 02 00 PM

//cc @deepakjosp

**Comment by karthiknmenon** [comment]
@deepakjosp _a Let's move this to `Helpers` as Praveen suggested. Also, let's add a link under Typography section to the helper section which shows them the helpers under Typography in neetoUI.

**Comment by deepakjosp** [comment]
@praveen-murali-ind  _a those helper class documentations are moved to the helpers folder in Foundation as suggested and also added a link at the end of Typography component documentation. Please go through it and let me know if you want to make any more changes. I think moving all typography helper documentation to one Typography file looks good. Please let me know what you think about this as well.

cc: @karthiknmenon

**Comment by praveen-murali-ind** [comment]
@deepakjosp _a I believe this is good to go. Could you please fix the contrast of the text in dark mode. 

Screenshot 2022-11-03 at 7 30 43 PM

Screenshot 2022-11-03 at 7 30 37 PM

**Comment by deepakjosp** [comment]
@praveen-murali-ind  _a fixed the above issue. The same problem was there in border radius stories. Fixed that as well. Apart from that set the bg color of boxes in box-shadow story to permanent white regardless of browser theme to better see the shadow. Please take a look.
cc: @karthiknmenon

**Review by karthiknmenon — APPROVED** [review]

**Review by praveen-murali-ind — APPROVED** [review]
LGTM

**Pull request merged**
