### PR TITLE
Table Improvements 

### LINKED ISSUE #599: Indicator for no data in Table component
Screenshot 2021-11-01 at 5 40 08 PM

@karthiknmenon _a

### LINKED ISSUE #606: Fix Avatar text in Table component.
@ajmaln _a Please take this up.

The `last_name` letter in Avatar is static here. It is showing as `o` for all last names.

Screenshot 2021-11-02 at 11 42 37 AM

//cc @karthiknmenon

### LINKED ISSUE #608: Allow click event in rows .
Now there is onRowClick , but it is only triggered when checking checkbox . It is better to be named as  row selection. 

It works when adding extra prop like this:
```

  onRow={row => {
            return {
              onClick: event => {
              }
            };
          }}

```

### LINKED ISSUE #621: Option to remove Checkbox from Tables
https://neetoui-v2.netlify.app/?path=/docs/components-table--template

here, the checkbox can be disabled by passing `rowSelection={false}` to the Table component. would be nice to have this on the docs.

Also, its possible to customize the Checkbox to radio by passing 
```jsx
rowSelection={{type: "radio"}}
```

### PR DESCRIPTION
**Pull request by karthiknmenon**
Fixes #621 ,
Fixes #599 , 
Fixes #608 , 
Fixes #606 

Ref - [Loom Video](https://www.loom.com/share/aa9f114546a34f1d8b89ee2d728060f7) 

UI Screenshots - 
- Table Layout 
image

- Single row selected
image

- Show IconButtons on hover
image

- Table with no checkbox for selecting rows 
image

- Loading state in table
image

### CODE REVIEW

**Comment by karthiknmenon** [comment]
makepr _t

**Comment by karthiknmenon** [comment]
@edwinbbu _a Please review. 
@praveen-murali-ind _a Please review. I have added CSS to show `iconButtons` in table rows only on hover.

**Comment by praveen-murali-ind** [comment]
> @edwinbbu _a Please review. @praveen-murali-ind _a Please review. I have added CSS to show `iconButtons` in table rows only on hover.

LGTM.  In my opinion we don’t need to hide and show `iconButtons`, In design also, the iconButtons are visible always. Let’s remove the icon size override in Button (icon size should be 16px).

**Comment by karthiknmenon** [comment]
@karthiknmenon _a Working on `iconButtons` suggestion.

**Comment by karthiknmenon** [comment]
@praveen-murali-ind _a I have made the required changes. Please review. 
Please assign it to Edwin for further review.

**Review by praveen-murali-ind — APPROVED** [review]
LGTM. @edwinbbu _a Please review and merge.

**Pull request merged**
