### PR TITLE
Fixes issues with the MultiEmailInput component when is creatale option is enabled.

### LINKED ISSUE #2348: Fix issue with `MultiEmailInput` component when `isCreatable` option is enabled
https://joseph-mathew.neetorecord.com/watch/5b6c7be6-7130-4e57-ad5c-6b4a9e14297a

@deepakjosp _a

### PR DESCRIPTION
**Pull request by deepakjosp**
Fixes #2348 

**Description**
- Fixed issues with the _MultiEmailInput_ component when `isCreatable` option is enabled.

**Checklist**

- [ ] ~I have made corresponding changes to the documentation.~
- [ ] ~I have updated the types definition of modified exports.~
- [x] I have verified the functionality in some of the neeto web-apps.
- [x] I have added tests that prove my fix is effective or that my feature works.
- [ ] ~I have added proper `data-cy` and `data-testid` attributes.~
- [x] I have added the necessary label (`patch`/`minor`/`major` - If package publish
      is required).

**Reviewers**

### CODE REVIEW

**Comment by deepakjosp** [comment]
@josephmathew900  _a please review.

**Review by josephmathew900 — COMMENTED** [review]
@deepakjosp _a https://joseph-mathew.neetorecord.com/watch/6817fb7a-fcac-4714-9eaa-824782adf816

**Comment by deepakjosp** [comment]
@josephmathew900  _a fixed. please review.

**Review by josephmathew900 — APPROVED** [review]
LGTM

**Pull request merged**
