### PR TITLE
Add prop-types to components

### LINKED ISSUE #457: Add prop-types to document the intended types of properties passed to components [v2]

### PR DESCRIPTION
**Pull request by vipul-goel**
Fixes #457

### CODE REVIEW

**Comment by vipul-goel** [comment]
_a @edwinbbu Please review

**Comment by karthiknmenon** [comment]
@vipul-goel _a Please rebase with master and assign it to Edwin.

**Comment by vipul-goel** [comment]
@edwinbbu _a Please review

**Comment by edwinbbu** [comment]
@praveen-murali-ind _a Please review the proptypes satisfies the requirement for the storybook.

**Comment by praveen-murali-ind** [comment]
LGTM. 

@edwinbbu _a Please review and merge.

**Review by edwinbbu — APPROVED** [review]

**Pull request merged**
