### PR TITLE
Removes the logic to get sort props from URL, accepting the props instead

### PR DESCRIPTION
**Pull request by sandip-mane**
1. Removed the code which took initial values from the URL
2. Added some changes to take the `sortBy` prop with `column` and `direction` from the parent components.

This solves the following problems:
https://youtu.be/bR8wJIMAYR0

### CODE REVIEW

**Comment by sandip-mane** [comment]
@edwinbbu _a please review.

**Comment by edwinbbu** [comment]
@sandip-mane Any reason why we are changing the URL when we are changing the sort values? I have seen the same in neetoChangelog as well. Initially, we didn't change the URL on changing the sort options.

**Comment by sandip-mane** [comment]
@edwinbbu so that the filters and sort are not reset on page reload. We can also share the URL with different users with applied filters and sort by default. 
For example, the following URL will show all published articles in ascending order by title.
https://spinkart.neetokb.net/admin/articles?column=title&direction=asc&state=published

**Comment by edwinbbu** [comment]
@sandip-mane _a
Please check https://www.loom.com/share/252403d9992646c885221a96af24645a

**Comment by sandip-mane** [comment]
@edwinbbu _a I have added back the state. Made it to keep in sync with the props and the local component changes. However, I could not run `yarn build`. Please run it before testing if you need to.

**Comment by edwinbbu** [comment]
cc @amaldinesh7

**Review by edwinbbu — APPROVED** [review]
LGTM!. Working fine in neetoChat.

**Pull request merged**
