### PR TITLE
Added the start value for email counter prop

### LINKED ISSUE #1177: Have email counter start counting from four
https://www.loom.com/share/12f198276b9b4a029e84c48a4ed9a25e

cc: @neerajdotname @karthiknmenon @amaldinesh7

### PR DESCRIPTION
**Pull request by Thejus-Paul**
Fixes #1177 

**Description**
 - Added: `startsFrom` to `counter` prop of _EmailInput_ component.
 
**Checklist**

- [x] I have performed a self-review of my code
- [x] I have made corresponding changes to the documentation
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added the necessary label (patch/minor/major - If package publish is required)
- [x] I have followed the suggested description format and styling

**Reviewers**

@amaldinesh7 _a

### CODE REVIEW

**Comment by amaldinesh7** [comment]
We shouldn't be hardcoding the threshold, that will be like a hidden logic. We can collect the threshold from the user. Please add a property under the prop count for the same. @Thejus-Paul _A

**Comment by amaldinesh7** [comment]
Please follow the description formal as mentioned in the PR template.

**Comment by amaldinesh7** [comment]
@Thejus-Paul _a Please do explain what does `startsFrom` do in storybook docs.

**Comment by Thejus-Paul** [comment]
@amaldinesh7 _a Please review.

**Review by amaldinesh7 — APPROVED** [review]

**Pull request merged**
