### PR TITLE
Updated Color Palette and Buttons

### LINKED ISSUE #896: Fix Image distortion in Avatar
@praveen-murali-ind _a

https://via.placeholder.com/200x100.png

Screenshot 2022-03-01 at 11 07 47 AM

Desired output (`object-fit: cover`)

Screenshot 2022-03-01 at 11 06 49 AM

### LINKED ISSUE #897: Update neetoUI color palette
@praveen-murali-ind _a

[Design Ref](https://www.figma.com/file/Ur7M4IquUbQ57Jpyx1ciMH/Neeto-UI-Kit?node-id=397%3A1321)

Screenshot 2022-03-01 at 11 56 19 AM

### LINKED ISSUE #898: Update Buttons Specs
@praveen-murali-ind _a

Design Ref - [Figma Link](https://www.figma.com/file/zhdsnPzXzr264x1WUeVdmA/02-Components?node-id=104%3A18)

**Current Specs**

Screenshot 2022-03-01 at 3 21 08 PM

Button styles - `primary`, `secondary `, `text `, `link `, `danger`
Button sizes - 32px - large, 28px - default
Icon sizes - 16px, 16px
Font sizes - 16px, 14px
Icon only button sizes - 16px, 16px

//cc @vysaghsekharbb  @goutham-subramanyam @karthiknmenon

### LINKED ISSUE #905: Remove tailwind dependency from neetoUI components
neetoUI should be used only for Storybook documentation. The components should all have their own custom classes.

#### Components

- [x] ActionDropdown
- [x] Button
- [x] Callout
- [x] Checkbox
- [x] ColorPicker
- [x] Dropdown
- [x] Email Input
- [x] Input
- [x] Label
- [x] PageLoader
- [x] Pagination
- [x] Radio
- [x] Spinner
- [x] Switch
- [x] Tab
- [x] Tag
- [x] Textarea
- [x] Accordion
- [x] Avatar
- [x] Date and Time
- [x] Select
- [x] Table

#### Overlays

- [x] Alert
- [x] Modal
- [x] Pane
- [x] Toastr
- [x] Tooltip

#### Layouts

- [x] AppSwitcher
- [x] Container
- [x] Header
- [x] Scrollable
- [x] SubHeader

### LINKED ISSUE #909: Improve Modal spacing
@praveen-murali-ind _a

Design Ref - [Figma link](https://www.figma.com/file/Ur7M4IquUbQ57Jpyx1ciMH/Neeto-UI-Kit?node-id=624%3A1711)

[Issue Description](https://github.com/bigbinary/neeto-ui/wiki/neetoUI-Audit#overlays)

//cc @vysaghsekharbb

### PR DESCRIPTION
**Pull request by praveen-murali-ind**
@goutham-subramanyam _a @vysaghsekharbb _a Please review.

Fixes #898 
 - [Storybook Documentation](https://deploy-preview-904--neetoui.netlify.app/?path=/story/components-button--all-variants) 
 - Added new Danger Button styles
 - Improved spacing in Button
 - CSS clean-up
 
Fixes #897 
- Updated neetoUI color palette
- Added utility classes for the newly added Accent colors

Fixes #896 

- Fixed Image distortion in Avatar

Fixes #909

- Modal spacing improvements 

Fixes #905

- Removed Tailwind dependency from neetoUI components

### CODE REVIEW

**Comment by vysaghsekharbb** [comment]
Looks fine.

**Review by goutham-subramanyam — APPROVED** [review]
LGTM.

**Comment by praveen-murali-ind** [comment]
@goutham-subramanyam _a

**Comment by goutham-subramanyam** [comment]
@praveen-murali-ind _a Fixed the storybook issue.

**Pull request merged**
