### PR TITLE
Shows color palette by default in the ColorPicker.

### LINKED ISSUE #2397: Display color palette by default in ColorPicker
Action item

- Update the color picker to display the color palette by default, using the color scheme provided in the attached Figma design.

[Figma](https://www.figma.com/design/iZqd7a5oh42RCdk9qZ2eXe/UI?node-id=872-379&t=7Zb1bG7A7Px4ppMf-4)

@josephmathew900 _a Could you please assign someone to work on it.

cc @deepakjosp

### PR DESCRIPTION
**Pull request by deepakjosp**
Fixes #2397 

**Description**
- Shows the color palette in the color picker by default.
- Updates the color list and the onChange handler to align with the color and onChange handler of the picker.
- Refactors and cleans up the onChange handlers and the associated functions.

**Checklist**

- [x] I have made corresponding changes to the documentation.
- [x] I have updated the types definition of modified exports.
- [x] I have verified the functionality in some of the neeto web-apps.
- [x] I have added tests that prove my fix is effective or that my feature works.
- [ ] ~I have added proper `data-cy` and `data-testid` attributes.~
- [x] I have added the necessary label (`patch`/`minor`/`major` - If package publish
      is required).

**Reviewers**

### CODE REVIEW

**Comment by deepakjosp** [comment]
@josephmathew900  _a please review.

**Review by praveen-murali-ind — APPROVED** [review]
LGTM. @josephmathew900 _A Please review.

**Review by josephmathew900 — COMMENTED** [review]
@deepakjosp _a https://joseph-mathew.neetorecord.com/watch/db8a6e4d-1e82-4e74-8c1a-682b27ae8310

**Comment by deepakjosp** [comment]
@josephmathew900  _a fixed. Please review.

**Review by josephmathew900 — APPROVED** [review]
LGTM

**Pull request merged**
