### PR TITLE
Make header z-index auto

### LINKED ISSUE #133: Header should be below pane/modal
We need to make this `auto`: https://github.com/bigbinary/neeto-ui/blob/99009f77f0aae39b9611e5db561c75ea35782f6f/lib/styles/layout/header.scss#L12

Problem:
Screenshot_20210104_170701

@edwinbbu I will make a fix for this by changing it into `z-index: auto`

### PR DESCRIPTION
**Pull request by yedhink**
Fixes #133 
@edwinbbu _a

Please review and update bundle. It's required as part of migration.

### CODE REVIEW

**Comment by edwinbbu** [comment]
@goutham-subramanyam _a

**Comment by goutham-subramanyam** [comment]
@yedhink _a Can you give me a context for this change ?

**Comment by yedhink** [comment]
@goutham-subramanyam _a

Fixes #134

**Comment by yedhink** [comment]
@goutham-subramanyam _a Refer #133 

Goto `Chat -> Contacts -> Columns(Subheader) -> New Attribute` to replicate error.

**Comment by goutham-subramanyam** [comment]
Closing as per https://github.com/bigbinary/neeto-ui/issues/133#issuecomment-753932831

**Pull request closed without merging**
