### PR TITLE
Added data-cy to missing elements

### LINKED ISSUE #1779: Add data-cy attributes to all missing elements
Current elements missing data-cy label:

|     Element                |         Current Selector                  |
|---------------------|--------------------------------|
| checkbox            | .neeto-ui-checkbox             |
| paneBody            | .neeto-ui-pane__body           |
| paneHeader          | .neeto-ui-pane__header         |
| selectOption        | .neeto-ui-react-select__option |
| toastCloseButton    | .neeto-ui-toastr__close-button |
| windowAlert         | #alert-box                     |
| toastIcon           | .Toastify__toast-icon          |
| paneModalCrossIcon  | .neeto-ui-pane__close          |
| alertModalCrossIcon | .neeto-ui-modal__close         |
| backDrop            | [data-testid='backdrop']       |
| tooltip             | .tippy-box                     |
| neetoUiSwitch | .neeto-ui-switch |
| placeholderFieldText | .neeto-ui-react-select__placeholder |
| optionSelectDropdownMenu | .neeto-ui-react-select__menu |
| dropdownContainer | .neeto-ui-react-select__value-container |
| modalHeader | .neeto-ui-modal__header |
| modalBody | .neeto-ui-modal__body |
| selectInputContainer | .neeto-ui-react-select__input-container |
| selectInput | .neeto-ui-react-select__input |
| inputError | .neeto-ui-input__error |
| modalFooter | .neeto-ui-modal__footer |
| modalHeaderDescription | .neeto-ui-modal__header-desc |

Table selectors:

|     Table element        |           current selector                 |
|-------------|--------------------------------|
| column   | td   |
| tableBody   | .ant-table-body                |
| tableHeader | .ant-table-thead th            |
| tableRow    | .ant-table-tbody tr            |
| spinner     | .ant-spin                      |
| heading  | tr > th |
| checkbox | .ant-checkbox-input |

Profile Selectors:

profileOptionsContainer: '[class="tippy-box sidebar-featured-tooltip__content"]'

Date Selectors: 

|     Table element        |           current selector                 |
|-------------|--------------------------------|
| todayButton | .ant-picker-today-btn |
| nowButton | .ant-picker-now-btn |
| nowClass | .ant-picker-now |
| datePanel | .ant-picker-date-panel |
| nextMonthNavigationButton | .ant-picker-header-next-btn |
| calendarsPanel | .ant-picker-panels |
| clearDate | .ant-picker-clear |
| meetingDateInput | .ant-picker-input |

### PR DESCRIPTION
**Pull request by KrishnapriyaSkk**
- Fixes #1779 

**Checklist**

- ~~[ ] I have made corresponding changes to the documentation.~~
- ~~[ ] I have updated the types definition of modified exports.~~
- [x] I have verified the functionality in some of the neeto web-apps.
- ~~[ ] I have added tests that prove my fix is effective or that my feature works~~
- [x] I have added the necessary label (patch/minor/major - If package publish
      is required).

**Reviewers**

### CODE REVIEW

**Comment by KrishnapriyaSkk** [comment]
@ajmaln _a
Please review.

**Review by ajmaln — COMMENTED** [review]
@KrishnapriyaSkk _a Added few suggestions

**Comment by KrishnapriyaSkk** [comment]
@ajmaln _a
I have made the suggested changes and also added `data-cy` for `tippy-box`. Please review.

**Review by ajmaln — APPROVED** [review]
@ajil-paul _a Could you please review

**Review by ajil-paul — APPROVED** [review]
@KrishnapriyaSkk _a LGTM.

**Pull request merged**
