### PR TITLE
NitroUI to NeetoUI

### LINKED ISSUE #20: Nitro => Neeto
https://github.com/bigbinary/neeto-ui/search?q=nitro

### PR DESCRIPTION
**Pull request by edwinbbu**
Fixes #20

### CODE REVIEW

**Comment by edwinbbu** [comment]
@vinay0x _a Please check the deployment failure.

**Comment by neerajdotname** [comment]
```
:37:21 AM: Build script success
5:37:21 AM: Failing build: Failed to build site
5:37:21 AM: Failed during stage 'building site': Deploy directory 'dist' does not exist
5:37:21 AM: Finished processing build request in 1m31.92616581s
```

**Comment by neerajdotname** [comment]
@edwinbbu I have invited you to netlify.

**Comment by vinay0x** [comment]
@edwinbbu Netlify was pointing to `neetui` branch instead of `neetoui-catalog`. This might've happened during the repo name changes. I've made the changes to the branch.

**Comment by vinay0x** [comment]
Closing and reopening the PR to trigger new build.

**Comment by vinay0x** [comment]
Got confused again. This repo was connected to our `catalog` app in Netlify after the name change. Instead it should've been connected to `neetoui-catalog` repo. I've made that change. This repo doesn't have anything to do with Netlify. Don't mind the failing tests. We'll remove Netlify integration from this repo. @edwinbbu _a

**Comment by edwinbbu** [comment]
@vinay0x _a please review

Changes
- I have updated package version to `0.58` to `0.60` since its a breaking change.
- Updated all references of nitroui to neetoui
- Build script updated to generate `neetoui.js` files

Tested out the branch in catalog as part of migration from nitro to neeto in catalog. 
Screenshot 2020-11-20 at 12 41 01 PM
Working fine.

**Review by vinay0x — APPROVED** [review]

**Pull request merged**
