### PR TITLE
Remove clear indicator

### LINKED ISSUE #1832: Remove `ClearIndicator: null` for `MultiEmailInput`
ref: https://github.com/bigbinary/neeto-molecules/issues/545

Remove `ClearIndicator` added in the custom components for `MultiEmailInput`

cc: @ajmaln

### PR DESCRIPTION
**Pull request by AkhilXavier95**
Fixes #1832 

image

~- [ ] I have made corresponding changes to the documentation.~
~- [ ] I have updated the types definition of modified exports.~
~- [ ] I have verified the functionality in some of the neeto web-apps.~
~- [ ] I have added tests that prove my fix is effective or that my feature works~
~- [ ] I have added the necessary label (patch/minor/major - If package publish is required).~

### CODE REVIEW

**Comment by AkhilXavier95** [comment]
@ajmaln _a please review this PR.

**Comment by ajmaln** [comment]
@praveen-murali-ind _a As discussed, please have a look

**Comment by praveen-murali-ind** [comment]
@AkhilXavier95 _a Can we use the same `clear` icon we are using for neetoUI Select component?

**Select icon vs existing icon difference**

Screenshot 2023-10-06 at 11 11 18 AM

Screenshot 2023-10-06 at 11 12 26 AM

**Comment by AkhilXavier95** [comment]
@ajmaln _a please review this PR.

**Review by ajmaln — APPROVED** [review]

**Pull request merged**
