### PR TITLE
Re-calculates the table height when select all rows callout is displayed.

### LINKED ISSUE #2286: Re-calculate the table height when`SelectAllRowsCallout` is displayed
https://abhay-ashokan.neetorecord.com/watch/1d721948-76de-4793-8d66-01edf4b941e8

UI _t 
@deepakjosp _a

### PR DESCRIPTION
**Pull request by deepakjosp**
Fixes #2286 

**Description**
https://deepak-jose.neetorecord.com/watch/ab0a7044-22de-4564-a015-0002ed390736

**Checklist**

- [ ] ~I have made corresponding changes to the documentation.~
- [ ] ~I have updated the types definition of modified exports.~
- [x] I have verified the functionality in some of the neeto web-apps.
- [ ] ~I have added tests that prove my fix is effective or that my feature works.~
- [ ] ~I have added proper `data-cy` and `data-testid` attributes.~
- [x] I have added the necessary label (`patch`/`minor`/`major` - If package publish
      is required).

**Reviewers**

### CODE REVIEW

**Comment by deepakjosp** [comment]
@praveen-murali-ind  _a please review.

https://deepak-jose.neetorecord.com/watch/ab0a7044-22de-4564-a015-0002ed390736

I tested, and it seems like we can permanently add the overflow hidden class to the TableWrapper component. Please let me know.

**Comment by deepakjosp** [comment]
@deepakjosp _a checking the failing tests.

**Comment by deepakjosp** [comment]
@praveen-murali-ind  _a tests are passing now.

**Review by praveen-murali-ind — APPROVED** [review]
LGTM.

**Comment by praveen-murali-ind** [comment]
@AbhayVAshokan _A Please review.

**Review by AbhayVAshokan — CHANGES_REQUESTED** [review]
@deepakjosp _a: https://abhay-ashokan.neetorecord.com/watch/e2840b95-a924-4f11-aa61-f1956bfa4ecd

**Comment by deepakjosp** [comment]
@AbhayVAshokan _a good catch. The problem was not visible in the products that I tested. I've refactored the height with hardcoded values instead of reading using the ref since often the ref will be empty. Please review.

**Pull request merged**
