### PR TITLE
Revert Formik data on clicking BlockNavigation continue

### LINKED ISSUE #1056: Formik data not getting reverted on clicking BlockNavigation Continue
@shamilsdq _a

### PR DESCRIPTION
**Pull request by shamilsdq**
Closes #1056

### CODE REVIEW

**Comment by amaldinesh7** [comment]
@shamilsdq _a Can you please post a video of testing the changes.

**Comment by shamilsdq** [comment]
Demo: [video](https://youtu.be/zrLkbSdHYAE)

**Comment by amaldinesh7** [comment]
@shamilsdq _a Please update the changelog.md file with the changes made in this PR. Keep the version number as 3.3.6

**Comment by shamilsdq** [comment]
Hi, @amaldinesh7 

I've added the changes to CHANGELOG.md file. Please review.

**Pull request merged**
