### PR TITLE
Allows user to freeze and unfreeze a column for horizontal scroll.

### LINKED ISSUE #2294: Allow user to freeze/unfreeze a column for horizontal scroll
Ref: https://github.com/bigbinary/neeto-form-web/issues/11271

### PR DESCRIPTION
**Pull request by deepakjosp**
Fixes #2294

**Description**
- Implements freeze/unfreeze column feature in the Table.

**Checklist**

- [x] I have made corresponding changes to the documentation.
- [x] I have updated the types definition of modified exports.
- [x] I have verified the functionality in some of the neeto web-apps.
- [x] I have added tests that prove my fix is effective or that my feature works.
- [ ] ~I have added proper `data-cy` and `data-testid` attributes.~
- [x] I have added the necessary label (`patch`/`minor`/`major` - If package publish
      is required).

**Reviewers**

### CODE REVIEW

**Comment by deepakjosp** [comment]
@josephmathew900  _a please review. There's a know bug within NeetoForm responses table. I've created an [issue](https://github.com/bigbinary/neeto-form-web/issues/11456) for that.

**Review by josephmathew900 — COMMENTED** [review]
@deepakjosp _a https://joseph-mathew.neetorecord.com/watch/ce740f24-2f41-4255-8fef-b063521c1382

**Comment by josephmathew900** [comment]
@deepakjosp Code changes LGTM. I have tested the issue with viewport resize and it is working fine now. The only issue remaining is with column jumping when freezing and unfreezing a column.

**Comment by deepakjosp** [comment]
@josephmathew900 the UI glitch is because of the inline style set to the CellContent component. I've created an issue to debug and fix the issue in [NeetoUI](https://github.com/bigbinary/neeto-ui/issues/2313). Let's merge this PR.

**Review by josephmathew900 — APPROVED** [review]
LGTM

**Pull request merged**
