### PR TITLE
Enhanced the customisability of Button component

### LINKED ISSUE #1856: Enhance the customisability of Button component
Part of https://github.com/bigbinary/neeto-ui/issues/1854

@goutham-subramanyam _a

cc: @praveen-murali-ind

### PR DESCRIPTION
**Pull request by goutham-subramanyam**
- Fixes #1856 

**Description**

**Checklist**

- [ ] ~I have made corresponding changes to the documentation.~
- [ ] ~I have updated the types definition of modified exports.~
- [ ] ~I have verified the functionality in some of the neeto web-apps.~
- [ ] ~I have added tests that prove my fix is effective or that my feature works~
- [ ] ~I have added the necessary label (patch/minor/major - If package publish
      is required).~

**Reviewers**

### CODE REVIEW

**Comment by goutham-subramanyam** [comment]
@praveen-murali-ind _a Please verify the changes as discussed in the standup call.

**Comment by goutham-subramanyam** [comment]
@praveen-murali-ind _a Please review.

**Comment by goutham-subramanyam** [comment]
@praveen-murali-ind As discussed, I have fixed the icon-only button padding for the `large` button. Merging the PR to the base branch.

Screenshot 2023-10-19 at 1 48 36 PM

**Comment by praveen-murali-ind** [comment]
@goutham-subramanyam The changes look great. Let's follow the same strategy for other components.

**Pull request merged**
