### PR TITLE
Removes Tags molecule from library and moved to neeto-tags-frontend

### LINKED ISSUE #1356: Move Tags molecule to neeto-tags package
@Thejus-Paul _a

### PR DESCRIPTION
**Pull request by deepakjosp**
Fixes #1356 

**Description**
- Removes Tags molecule from library and moved to [neeto-tags-frontend](https://github.com/bigbinary/neeto-tags-frontend)

**Checklist**

- [x] I have performed a self-review of my code
- [x] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added the necessary label (patch/minor/major - If package publish is required)
- [x] I have followed the suggested description format and styling

**Reviewers**

### CODE REVIEW

**Comment by deepakjosp** [comment]
@akhil-gautam  _a could you please review this PR?

**Comment by akhil-gautam** [comment]
@amaldinesh7 _A Should we merge this once the neeto-tags-frontend changes are rolled out to all the neeto products using it?

**Comment by amaldinesh7** [comment]
> @amaldinesh7 _A Should we merge this once the neeto-tags-frontend changes are rolled out to all the neeto products using it?

@akhil-gautam Not necessarily. By we can take the risk-free approach. Can you please coordinate adding the same to neeto-tags-frontend?

@deepakjosp _A Please remove `molecules.d.ts` file as welll.

**Comment by deepakjosp** [comment]
@amaldinesh7  _a changes on dependent projects using Tags from neetoUI are rolled out.
cc: @akhil-gautam

**Pull request merged**
