### PR TITLE
Updated Modal styles to match the design

### LINKED ISSUE #482: Update Modal component to match the design
@praveen-murali-ind  _a

### PR DESCRIPTION
**Pull request by praveen-murali-ind**
Fixes #482 

@karthiknmenon _a Could you please review.

//cc @edwinbbu

### CODE REVIEW

**Comment by karthiknmenon** [comment]
@praveen-murali-ind _a Modal styles look good. Could you please look into consistency in `Button` component with respect to design?

**Comment by edwinbbu** [comment]
Let's hold this PR until https://github.com/bigbinary/neeto-ui/pull/489 is merged. Else there would be conflicts on the other PR.

**Comment by karthiknmenon** [comment]
@praveen-murali-ind We can continue the work on this PR now that #489 is merged.

**Comment by praveen-murali-ind** [comment]
Updated Button styles. 

@karthiknmenon _a Please review.

**Review by karthiknmenon — APPROVED** [review]
LGTM.

**Pull request merged**
