### PR TITLE
Fixed column info popover style

### LINKED ISSUE #2062: Fix the style of column info popover
Screenshot 2024-01-05 at 5 46 53 PM

Screenshot 2024-01-05 at 6 54 32 PM

cc: @praveen-murali-ind  @goutham-subramanyam

### PR DESCRIPTION
**Pull request by nitinprojects**
- Fixes #2062

**Description**
### After
Screenshot 2024-01-05 at 6 41 38 PM

Screenshot 2024-01-05 at 6 59 07 PM

**Checklist**

~- [ ] I have made corresponding changes to the documentation.~
~- [ ] I have updated the types definition of modified exports.~
~- [ ] I have added tests that prove my fix is effective or that my feature works~
- [x] I have verified the functionality in some of the neeto web-apps. (**neetoDesk - Automations table)**
- [x] I have added the necessary label (patch/minor/major - If package publish
      is required).

**Reviewers**
@praveen-murali-ind _a Please review.

### CODE REVIEW

**Comment by nitinprojects** [comment]
@praveen-murali-ind _a Please review.

**Review by praveen-murali-ind — APPROVED** [review]

**Comment by praveen-murali-ind** [comment]
@nitinprojects _a I have verified that the default padding for the neetoUI popover is functioning correctly. However, overrides are occurring only in the Table Popover. Let's address this specific override without modifying the default popover padding.

The fix in this PR is altering the default popover padding, which is not the intended spacing.

Before
Screenshot 2024-01-05 at 10 35 25 PM

After
Screenshot 2024-01-05 at 10 35 08 PM

**Comment by nitinprojects** [comment]
@goutham-subramanyam _a Please review, I have made the necessary changes.

Screenshot 2024-01-12 at 10 08 03 AM
Screenshot 2024-01-12 at 10 08 33 AM

**Comment by goutham-subramanyam** [comment]
@nitinprojects I have updated the code to handle the padding without an additional classname. Please check the commit https://github.com/bigbinary/neeto-ui/pull/2063/commits/2bd25618f6a01415d6494cb512d1a85259148b77

@praveen-murali-ind I have verified the change in both neetoUI storybook and neetoDesk using yalc

Screenshot 2024-01-17 at 6 19 31 PM

Screenshot 2024-01-17 at 6 19 22 PM

**Pull request merged**
