### PR TITLE
Add data cy attribute

### LINKED ISSUE #1950: Add data-cy for textarea in ticket fields
Add data-cy for textarea in ticket field while creating a new ticket. Expected selector: ```data-cy=`{hyphonize(label)}-text-input` ```
Ref: 
Screenshot 2023-11-05 at 10 46 44 PM

### PR DESCRIPTION
**Pull request by AkhilXavier95**
- Fixes #1950 

**Description**
Added: data-cy attribute to TextArea

**Checklist**

~- [ ] I have made corresponding changes to the documentation.~
~- [ ] I have updated the types definition of modified exports.~
~- [ ] I have verified the functionality in some of the neeto web-apps.~
~- [ ] I have added tests that prove my fix is effective or that my feature works~
- [x] I have added the necessary label (patch/minor/major - If package publish
      is required).

**Reviewers**

### CODE REVIEW

**Comment by AkhilXavier95** [comment]
@ajmaln _a please review this PR.

**Review by ajmaln — APPROVED** [review]
@ajil-paul _a Please review

**Review by ajil-paul — APPROVED** [review]
LGTM. @VarunSriram99 _a Please review.
cc @shreyakurian02

**Review by VarunSriram99 — APPROVED** [review]
LGTM

**Pull request merged**
