### PR TITLE
Added scrolling to EmailInput

### LINKED ISSUE #1097: Make Email Input scrollable
## issue

As per the discussion with @karthiknmenon and @Thejus-Paul 

The [EmailInput](https://github.com/bigbinary/neeto-ui/blob/9e799ddd97ecb71081b9bf75d45b2cb8cd0d2319/lib/components/EmailInput.js#L76) component doesn't set a limit on the container so when entering a large number of emails, it overflows its parent containers. The component can be made scrollable to prevent this.

### PR DESCRIPTION
**Pull request by mohit-s96**
closes #1097

### CODE REVIEW

**Comment by mohit-s96** [comment]
@Thejus-Paul _a please review.

**Comment by mohit-s96** [comment]
@Thejus-Paul _a please review the changes

**Review by amaldinesh7 — APPROVED** [review]
@mohit-s96 _a Please add the change to Changelog.md. You will find the points to consider white writing a changelog there itself.

**Comment by mohit-s96** [comment]
@amaldinesh7  _a. Updated the Changelog. Please review.

**Pull request merged**
