### PR TITLE
Make all headers visible

### LINKED ISSUE #126: Table stylesheet needs modifications
Opacity of last table header should be 100. Otherwise it wont show up.

https://github.com/bigbinary/neeto-help-web/pull/9162#issuecomment-751625505

@yedhink _a

cc: @edwinbbu @goutham-subramanyam

### PR DESCRIPTION
**Pull request by yedhink**
Fixes #126 

@edwinbbu _a
Please review. When this is merged and bundle is updated, then [this issue](https://github.com/bigbinary/neeto-help-web/pull/9162#issuecomment-751625505) in neeto-help should get fixed.

cc: @goutham-subramanyam

### CODE REVIEW

**Comment by edwinbbu** [comment]
@goutham-subramanyam _a please review

**Comment by goutham-subramanyam** [comment]
@yedhink _a Instead of this, just sync the table.scss styles from NeetoHelp. That will fix the issue.

**Comment by yedhink** [comment]
@goutham-subramanyam _a

Please review.

**Review by goutham-subramanyam — APPROVED** [review]
LGTM.

**Pull request merged**
